# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m4t.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tm4t.proto\x12\x03m4t\";\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x10\n\x08\x61udio_id\x18\x03 \x01(\t\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32I\n\x0bTextToAudio\x12:\n\x12\x43onvertTextToAudio\x12\x10.m4t.TextRequest\x1a\x12.m4t.AudioResponseB$Z\"github.com/omnigram-server/api/m4tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'm4t_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/omnigram-server/api/m4t'
  _globals['_TEXTREQUEST']._serialized_start=18
  _globals['_TEXTREQUEST']._serialized_end=77
  _globals['_AUDIORESPONSE']._serialized_start=79
  _globals['_AUDIORESPONSE']._serialized_end=114
  _globals['_TEXTTOAUDIO']._serialized_start=116
  _globals['_TEXTTOAUDIO']._serialized_end=189
# @@protoc_insertion_point(module_scope)
